### ISSUE TITLE
Initial release TODO list

### ISSUE THREAD

**Issue by forrestlaine** [forrestlaine/QPN.jl#1]
- [ ] Test robust_constrained example
- [ ] Port bouncing polygon, other test examples into new symbolic definition framework, examples folder
- [ ] Define proper unit tests
- [ ] Complete low-dim min-norm implementation -- will possibly require a refactor of how min-norm gets called.
- [ ] clean-up
- [ ] write minimal docs
